"""Canonical entity and edge kinds for the orchestration graph (see ADR-004)."""

from __future__ import annotations

ENTITY_KINDS: frozenset[str] = frozenset(
    {
        "objective",
        "initiative",
        "epic",
        "story",
        "task",
        "repo",
        "branch",
        "change_request",
        "commit",
        "build",
        "artifact",
        "release",
        "environment",
        "test_run",
        "test_plan",
        "test_suite",
        "test_case",
        "defect",
        "security_finding",
        "compliance_exception",
        "control",
        "vulnerability",
        "incident",
        "service",
        "postmortem",
        "evidence",
        "scenario",
        "workstream",
        "demand_signal",
        "scoped_commitment",
        "contributor",
        "gate",
        "methodology_artifact",
        "decision_record",
        "review_pack",
        "assay_packet",
        # Sprint B3 — agentic bridge (governed agent execution, observability)
        "versona_family",
        "versona_profile",
        "tasklet",
        "recipe",
        "launch_pack",
        "agent_run",
        "agent_step",
        "agent_output",
        "approval_request",
        "policy_rule",
        "execution_target",
        "drift_report",
        "rules_manifest",
        "prompt_template",
        # Sprint B4 — ceremony bridge (methodology-neutral intents, templates, instances)
        "ceremony_intent",
        "ceremony_template",
        "ceremony_mapping",
        "ceremony_instance",
        "delivery_mode",
        "ceremony_output",
        "participant_role",
        "moderator_role",
        "signoff_record",
        "followup_action",
        "required_artifact_ref",
        "decision_binding_rule",
        # Sprint B5 — Cursor / Claude handoff loop (package → session → return → graph)
        "handoff_package",
        "handoff_target",
        "prompt_bundle",
        "context_bundle",
        "execution_session",
        "execution_return",
        "sync_checkpoint",
        "output_manifest",
        "file_change_summary",
        "code_review_ref",
        "build_test_return",
        # Sprint B6 — PDLC outcome bridge (launch → signals → learning → demand)
        "launch_record",
        "outcome_signal",
        "metric_snapshot",
        "experiment_result",
        "customer_feedback_ref",
        "support_signal",
        "adoption_signal",
        "retention_signal",
        "satisfaction_signal",
        "revenue_proxy_signal",
        "learning_summary",
        "followon_ore_candidate",
    }
)

EDGE_KINDS: frozenset[str] = frozenset(
    {
        "contains",
        "blocks",
        "implements",
        "tests",
        "deploys",
        "deploys_to",
        "affects",
        "caused_by",
        "mitigates",
        "documented_by",
        "targets",
        "depends_on",
        "allocated_to",
        "validates",
        "raised_defect",
        "accepted_risk_for",
        "satisfies",
        "triggered_after",
        "analyzes",
        "impacts",
        "originates_from",
        "decomposes_to",
        "reviewed_by",
        "evidenced_by",
        "gated_by",
        "supersedes",
        "derived_from",
        "blocked_by",
        "aggregates",
        "references",
        "approves",
        # B3 agentic — run/recipe/tasklet/output/approval wiring
        "executes",
        "invokes",
        "emits",
        "seeks_approval",
        "constrains",
        # B4 ceremony wiring
        "instantiates",
        "realizes_intent",
        "yields_output",
        "requires_input",
        "follows_up_with",
        # B5 handoff loop
        "scopes_handoff",
        "session_for",
        # B6 PDLC outcome loop
        "launch_for",
        "outcome_observed",
        "proposes_followon",
        "bridges_to_demand",
    }
)
