#!/usr/bin/env bash
# Generate a random bearer token, save Fleet URL + token for Lenses (workspace .lenses-local),
# and write a gitignored env file you can source when starting forge-fleet.
#
# Usage:
#   ./scripts/bootstrap-local-fleet-dev.sh
#   export LENSES_WORKSPACE_ROOT=/path/to/workspace   # optional; default: parent of this repo
#
# Then start Fleet (from forge-fleet checkout):
#   set -a && source /path/to/forge-lenses/scripts/.local-fleet-bearer.env && set +a && python3 -m fleet_server --host 127.0.0.1 --port 18765
#
# Start Lenses as usual; Studio → Forge Fleet should already show the URL (token masked in GET).

set -euo pipefail
REPO_ROOT=$(cd "$(dirname "$0")/.." && pwd)
WS_RAW="${LENSES_WORKSPACE_ROOT:-}"
if [[ -n "${WS_RAW}" ]]; then
  WS=$(cd "${WS_RAW}" && pwd)
else
  WS=$(cd "${REPO_ROOT}/.." && pwd)
fi

TOKEN=$(python3 -c "import secrets; print(secrets.token_urlsafe(48))")
FLEET_URL="${FLEET_DEV_URL:-http://127.0.0.1:18765}"
FLEET_URL="${FLEET_URL%/}"

mkdir -p "${WS}/.lenses-local"
SETTINGS="${WS}/.lenses-local/fleet-settings.json"
python3 - "${WS}" "${TOKEN}" "${FLEET_URL}" <<'PY'
import json, os, sys
from pathlib import Path

ws, token, base = Path(sys.argv[1]), sys.argv[2], sys.argv[3]
p = ws / ".lenses-local" / "fleet-settings.json"
data = {
    "version": 2,
    "nodes": [
        {
            "id": "local-primary",
            "base_url": base,
            "bearer_token": token,
            "enabled": True,
            "priority": 10,
            "max_cpu_percent": None,
            "max_memory_percent": None,
        }
    ],
}
p.parent.mkdir(parents=True, exist_ok=True)
p.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")
try:
    os.chmod(p, 0o600)
except OSError:
    pass
try:
    os.chmod(p.parent, 0o700)
except OSError:
    pass
print(p)
PY

ENV_FILE="${REPO_ROOT}/scripts/.local-fleet-bearer.env"
{
  echo "# Generated by scripts/bootstrap-local-fleet-dev.sh — do not commit."
  printf 'export FLEET_BEARER_TOKEN=%q\n' "${TOKEN}"
} >"${ENV_FILE}"
chmod 600 "${ENV_FILE}"

echo "[bootstrap-local-fleet] workspace_root=${WS}"
echo "[bootstrap-local-fleet] fleet-settings -> ${SETTINGS}"
echo "[bootstrap-local-fleet] source for Fleet server -> ${ENV_FILE}"
echo "[bootstrap-local-fleet] fleet base URL -> ${FLEET_URL}"
